receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  tail_sampling:
    decision_wait: 10s
    num_traces: 5000
    policies:
      [
        {
          name: sampling-policy,
          type: probabilistic,
          probabilistic: { sampling_percentage: 25 },
        }
      ]

exporters:
  coralogix:
    domain: "${CORALOGIX_DOMAIN}"
    private_key: "${PRIVATE_KEY}"
    application_name: "${APP_NAME}"
    subsystem_name: "${SUB_SYS}"
    application_name_attributes:
      - "aws.ecs.cluster"
      - "aws.ecs.task.definition.family"
    subsystem_name_attributes:
      - "aws.ecs.container.name"
      - "aws.ecs.docker.name"
      - "docker.name"
    timeout: 30s

extensions:
  health_check:
  pprof:

service:
  extensions:
    - health_check
    - pprof
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [coralogix]
  telemetry:
    logs:
      level: warn
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888 