Parameters:
  CoralogixRegionAlias:
    Type: String
    Description: The Alias for the Coralogix region, possible options are [us1, us2, eu1, eu2, ap1, ap2, custom]
    AllowedValues:
      - us1
      - us2
      - eu1
      - eu2
      - ap1
      - ap2
      - custom
  CustomCoralogixAccount:
    Type: String
    Description: In case you want to use a custom coralogix account, enter the aws account id that you want to use.
    Default: ''

Conditions:
  IsRegionUs2: !Equals
    - Ref: CoralogixRegionAlias
    - us2
  IsCustomAccount: !Not
    - !Equals
      - Ref: CustomCoralogixAccount
      - ''

Resources:
  CoralogixSIEMExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Coralogix-SIEM-Execution-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub
                - 'arn:aws:iam::${aws_account_id}:role/siem-service'
                - aws_account_id: !If
                    - IsCustomAccount
                    - !Ref CustomCoralogixAccount
                    - !If
                      - IsRegionUs2
                      - '739076534691'
                      - '625240141681'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CoralogixSIEMPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: SIEM
                Resource: ["*"]
                Effect: Allow
                Action:
                  - "s3:GetBucketPublicAccessBlock",
                  - "s3:GetBucketTagging",
                  - "ec2:DescribeInstances",
                  - "lambda:ListFunctions",
                  - "dynamodb:ListTagsOfResource",
                  - "s3:GetBucketAcl",
                  - "ecs:DescribeClusters",
                  - "s3:GetEncryptionConfiguration",
                  - "s3:ListAllMyBuckets",
                  - "lambda:ListTags",
                  - "dynamodb:DescribeTable",
                  - "rds:DescribeDBInstances",
                  - "redshift:DescribeClusters",
                  - "eks:DescribeCluster",
                  - "ecs:ListContainerInstances",
                  - "eks:ListClusters",
                  - "ec2:DescribeSubnets",
                  - "s3:GetBucketLocation",
                  - "rds:DescribeDBClusters",
                  - "redshift:DescribeClusterParameters",
                  - "ecs:ListClusters"