AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create CloudMap namespace for OpenTelemetry services'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Existing VPC for the CloudMap namespace

Resources:
  OtelCloudMapNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: cx-otel
      Vpc: !Ref VpcId
      Description: "Cloud Map namespace for OpenTelemetry services"

Outputs:
  CloudMapNamespaceId:
    Description: "Cloud Map namespace ID"
    Value: !Ref OtelCloudMapNamespace
    Export:
      Name: !Sub "${AWS::StackName}-namespace-id"
  
  CloudMapNamespaceName:
    Description: "Cloud Map namespace name"
    Value: !Ref OtelCloudMapNamespace
    Export:
      Name: !Sub "${AWS::StackName}-namespace-name"
